apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  namespace: dev
  labels:
    app: backend
spec:
#  replicas: 4
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine