apiVersion: v1
kind: Pod
metadata:
  name: cpu-test-mayorquelimit
spec:
  containers:
    - name: stress
      image: vish/stress
      resources:
        limits:
          # cpu: '1000m'
          cpu: '1'
        requests:
          # cpu: '500m'
          cpu: '0.5'
      args:
        - -cpus
        - '2'
---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-test-limitmayorquecpus
spec:
  containers:
    - name: stress
      image: vish/stress
      resources:
        limits:
          cpu: '100'
        requests:
          cpu: '100'
      args:
        - -cpus
        - '2'