apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-app-backend-dev
  namespace: dev
  labels:
    app: app
    type: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app
      type: backend
  template:
    metadata:
      labels:
        app: app
        type: backend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app-backend-dev
  namespace: dev
  labels:
    app: app
    type: backend
spec:
  selector:
    app: app
    type: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80