apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  namespace: dev
  labels:
    app: backend
spec:
#  replicas: 3
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              memory: '500M'
              cpu: '500m'
            limits:
              memory: '500M'
              cpu: '500m'