apiVersion: v1
kind: Pod
metadata:
  name: cpu-test
spec:
  containers:
    - name: stress
      image: vish/stress
      resources:
        limits:
          # cpu: '1000m'
          cpu: '1'
        requests:
          # cpu: '500m'
          cpu: '0.5'
      args:
        - -cpus
        - '2'