apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-app-client
  labels:
    app: golang-app
    app-type: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang-app
      app-type: frontend
  template:
    metadata:
      labels:
        app: golang-app
        app-type: frontend
    spec:
      containers:
        - name: frontend
          # Por defecto Kubernetes va a buscar la imágen en internet
          imagePullPolicy: IfNotPresent
          image: golang-app-client:v1
---
apiVersion: v1
kind: Service
metadata:
  name: golang-app-client
  labels:
    app: golang-app
    app-type: frontend
spec:
  type: NodePort
  selector:
    app: golang-app
    app-type: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80