apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: dev
spec:
  limits:
    - max:
        memory: '1Gi'
        cpu: '1'
      min:
        memory: '100M'
        cpu: '100m'
      type: Container