apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-pod-reader
  namespace: default
subjects:
  - kind: ServiceAccount
    name: my-service-account
    apiGroup: ''
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io