apiVersion: v1
kind: Pod
metadata:
  name: podtest
spec:
  containers:
    - image: nginx:alpine
      name: nginex
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest2
spec:
  containers:
    - image: nginx:alpine
      name: nginex