apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  capacity:
    storage: '10Gi'
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/test'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume
  labels:
    type: local
spec:
  selector:
    matchLabels:
      type: local
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '10Gi'
