apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: vol-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: vol-config
          configMap:
            name: nginx-conf
            items:
              - key: nginx
                path: default.conf
