apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1-volume
  labels:
    type: local1
spec:
  storageClassName: manual
  capacity:
    storage: '10Gi'
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/test1'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2-volume
  labels:
    type: local2
spec:
  storageClassName: manual
  capacity:
    storage: '10Gi'
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/test2'