apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume
  labels:
    type: local
spec:
  selector:
    matchLabels:
      type: local2
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '10Gi'
